### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by antoniouras** [theSage21/handwritten#7]
Dear developers, I find an error when running the simple example provided in the doc:

python get_hand.py -t "Homework could have been easier" -s 2 -c 0,0,200 -b 0.85

  File "get_hand.py", line 51
    print('.', end='')
                  ^
SyntaxError: invalid syntax

Do you have any hint?

Best regards,
Antonio

**Comment by theSage21** [comment]
This could possibly be coming from the use of python 2.7

**Comment by antoniouras** [comment]
Thanks... is there anything I can do to overcome the problem?

**Comment by theSage21** [comment]
You can install python 3.x
That should take care of the problem.

**Comment by antoniouras** [comment]
Thanks, I've installed python3, now I get this message:

Traceback (most recent call last):
  File "get_hand.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Shall I install anything else?

**Comment by theSage21** [comment]
Hmm. I missed adding this to the README. You need to install [requests](http://docs.python-requests.org/en/master/) and [Pillow](https://pillow.readthedocs.io/en/latest/) to run the demo.

**Comment by antoniouras** [comment]
Thanks, now the script starts doing its job! However, I still don't manage to get the output figure:

......
Creating images folder
Starting handwriting generation

0  -  Homework could have been easier.Traceback (most recent call last):
  File "get_hand.py", line 111, in <module>
    command_line()
  File "get_hand.py", line 105, in command_line
    add_color(color, image_out)
  File "get_hand.py", line 60, in add_color
    img = Image.open(image_out)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'images/0.png'


The file images/0.png is created, but it is not readable. Am I missing something?

**Comment by theSage21** [comment]
Hmm. I haven't faced this before.

**Comment by antoniouras** [comment]
If it can help, I work on Mac Sierra 10.12.6...

**Comment by theSage21** [comment]
Are you able to open it with some kind of image viewer?

**Comment by antoniouras** [comment]
No... the message is always that the file is damaged or corrupted.

**Comment by theSage21** [comment]
In that case it's probably not getting written properly. I last verified this before the code was updated for color. Can @ritiek help out?

**Comment by ritiek** [comment]
Sorry, I am a bit busy at the moment. I'll investigate more on this soon.

BTW, I think this is a problem with saving the generated image locally (and not with color option, I guess). @antoniouras Can you try running the same command but replacing color option with `-c 0,0,0`?

**Comment by antoniouras** [comment]
Hello, sorry for the delay! Thanks for the suggestion, I've tried with the -c 0,0,0 option and I have the following output messages:

Starting handwriting generation
0  -  Homework could have been easier.|

Apparently, no error message this time. However, the output file is still not readable (file damaged). I'm attaching it to the this message, in case it could be useful. Here it is: 
![0](https://user-images.githubusercontent.com/35934218/36005341-82eec4fa-0d37-11e8-8d59-a92515cd04e3.png)

**Comment by ritiek** [comment]
Is it just me or is something wrong with http://www.cs.toronto.edu/~graves/handwriting.cgi (does not generate handwriting anymore)?

**Comment by theSage21** [comment]
I haven't checked. It might have gone down.

**Comment by antoniouras** [comment]
I confirm, the http://www.cs.toronto.edu/~graves/handwriting.cgi generator doesn't work...

**Comment by theSage21** [comment]
Hmm. I don't have a free server right now to host the actual neural net. I've mailed Graves about this. Let's see what turns up. Otherwise we could write a small net and put it in this repo, thereby eliminating the network calls.

**Comment by fleuryfontaine** [comment]
Hi, I have the same problem than @antoniouras the png is corrupted. I'm on PC, windows 8 with python 3.6.4 I was a fan of Graves website and was really happy to find out you did a easy usable version it's a great idea !  Hope you can find a fix, good luck.

**Comment by theSage21** [comment]
Since Graves' site is down and there has been no reply so far to queries; I've created a free heroku app for now. It's slow but it gets the job done. I haven't tested for full backward compatibility though so @fleuryfontaine and @antoniouras, you might want to open new issues regarding the new server.

Go easy on it though :smile: it isn't a big machine.
